module.exports = {
  // 2d
  circle: require('./2d/circle'),
  oval: require('./2d/oval'),
  triangle: require('./2d/triangle'),
  rectangle: require('./2d/rectangle'),
  polygon: require('./2d/polygon'),
  pentagon: require('./2d/pentagon'),
  hexagon: require('./2d/hexagon'),
  // 3d
  cone: require('./3d/cone'),
  cube: require('./3d/cube'),
  cylinder: require('./3d/cylinder'),
  polyhedron: require('./3d/polyhedron'),
  pyramid: require('./3d/pyramid'),
  sphere: require('./3d/sphere'),
  tetrahedron: require('./3d/tetrahedron'),
  // others
  angle: require('./angle'),
  calc: require('./calc'),
  calculus: require('./calculus'),
  equation: require('./equation'),
  matrix: require('./matrix'),
  others: require('./others'),
  progress: require('./progress'),
  vector: require('./vector'),
  // version
  version: require('../package.json').version
}
